[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
infrastructure = { path = "../infrastructure" }
geometry = { path = "../geometry" }
display = { path = "../display" }
interaction = { path = "../interaction" }
storage = { path = "../storage" }


